# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nilsonlinux
email: nilsonlinux@gmail.com
description: "Nilsonlinux Blog."
baseurl: "/blog"
url: "https://nilsonlinux.github.io"
twitter_username: nilsonlinux
github_username: nilsonlinux

# Build settings
markdown: kramdown
permalink: /:title/
